Material ID's, MetaItem Restructure and texture Changes
Gregtech-Beyond/gregtech-beyond-core pull request #21
Opened 2024-05-14 18:36 UTC by jude123412

2024-05-14 19:20 UTC, tekcay requested changes

2024-05-14 19:20 UTC, tekcay commented on src/main/java/gtb/common/item/GTBMetaItems.java
> -    public static MetaItem<?>.MetaValueItem ASTRO_MINER;
I don't see the point in removing those constants as they make getting items much easier.

2024-05-14 19:20 UTC, tekcay commented on src/main/java/gtb/loaders/recipe/OilLine.java
> +                .output(GTBMetaItems.getByNameOrId("paraffin_wax"), 1).fluidOutputs(Diesel.getFluid(1000))
See here you have to call it by a string which is very prone to error. The initial method won't get an error and it is much more convenient to use, just type `GTBItems`, dot and you can access all the items.

2024-05-14 19:20 UTC, tekcay commented on dependencies.gradle
this should be in another branch as it has nothing to do with the pr name, create another branch. Plus this crash has not been reported so far, can you open an issue ?

2024-05-14 20:07 UTC, jude123412 commented on src/main/java/gtb/common/item/GTBMetaItems.java
> -    public static MetaItem<?>.MetaValueItem ASTRO_MINER;
well I learned the hard way that changing that makes it harder to retrieve items

2024-05-14 20:14 UTC, jude123412 commented
Sorry Didn't mean to close the pull request, I have reverted the changes from the metaItems and will use that from now on :)

2024-05-14 20:15 UTC, jude123412 commented on dependencies.gradle
Reverted the MetaItem Changes to previous version

2024-05-14 20:16 UTC, tekcay commented
@jude123412 yeah figured it out haha

2024-05-14 20:17 UTC, jude123412 commented
yup metaitems will be made like that from now on :)

2024-05-14 20:19 UTC, jude123412 commented
should all be fixed... hopfully

2024-05-15 08:20 UTC, jude123412 commented on dependencies.gradle
Interesting does the dependency changes cause a crash for you?

2024-05-15 08:38 UTC, jude123412 commented
Closing pull request as its a mess, Ill make a new one.

2024-05-15 08:38 UTC, closed without merging