Photolithography branch
Gregtech-Beyond/gregtech-beyond-core pull request #24
Opened 2024-05-15 13:16 UTC by BLocky104

fully finish Photolithography, no crashes ETC, textures and other stuff will be done in the following branch of mine

2024-05-15 13:27 UTC, BLocky104 commented
Reviewed and resolved every problem

2024-05-15 17:18 UTC, jude123412 approved these changes
Looks all good to me 👍

2024-05-15 17:38 UTC, tekcay requested changes
Errors loading multiple items texture due to invalid models.
Errors in recipes in Photolithography

2024-05-15 17:38 UTC, tekcay commented on src/main/java/gtb/loaders/recipe/Photolithography.java
> +                .output(NANO_PIC_WAFER)
this recipe and many others are not working, `Recipe output are empty`.

2024-05-15 17:42 UTC, tekcay reviewed
still missing some :p

2024-05-15 18:03 UTC, jude123412 commented
And thats why 2 people are needed for changes

2024-05-16 10:10 UTC, jude123412 approved these changes

2024-05-16 13:19 UTC, jude123412 approved these changes

2024-05-16 21:24 UTC, tekcay commented
@BLocky104 

- Last recipe in `Photolithography` :
```java
        ASSEMBLER_RECIPES.recipeBuilder()
                .input(CONTROLLED_SHAPED_NAQUADRIA_CHARGE)
                .input(NAQUADRIA_CHARGE)
                .output(CONTROLLED_SHAPED_NAQUADRIA_CHARGE)
                .EUt(250) // TODO was missing, I don't which value you want
                .duration(120)
                .circuitMeta(2)
                .buildAndRegister();
```

the EUt value was missing, just added a arbitrary value.
                
- some textures are missing : 

    - shaped_high_energy_gamma_shield
    - hasoc_lithography_mask
    - naquadria_charge
    - engraved_oganesson_wafer
    - photopolymer_plate

2024-05-16 21:33 UTC, jude123412 approved these changes

2024-05-17 17:56 UTC, jude123412 approved these changes

2024-05-17 20:18 UTC, tekcay approved these changes

2024-05-17 20:25 UTC, merged