Material Icon Sets, Damascus Steel Line Finish and Finally Damascus Steel Icon Sets
Gregtech-Beyond/gregtech-beyond-core pull request #25
Opened 2024-05-16 13:22 UTC by jude123412

Added Class Files for Material Icon Set Creation along with Damascus Icon Sets Added Textures for all Damascus Icon Sets
Added Chemical Formula for Damascus Steel
Finished Damascus Steel Line, Now produces Ingots instead of Plates 
Changes to various code to make it more clean

2024-05-16 17:48 UTC, tekcay requested changes
Everything's good. I'd just appreciate the little about IconSet stuff, but nothing too crazy, tell me what you think :)
Oh and finally a launch log without red lines !

2024-05-16 17:48 UTC, tekcay commented on src/main/java/gtb/api/unification/materials/GTBMaterialIconSetAddition.java
What I would suggest here to put everything IconSet related to the same class, `GTBMaterialIconType`. Move your `init()` method in there and rename it to something like `set()` or something. It avoids creating multiple classes

2024-05-16 17:48 UTC, tekcay commented on src/main/java/gtb/api/unification/materials/GTBMaterialSetFormula.java
Call me picky, but here I would name the class `GTBMaterialFormula` and the method to `set()`. That's my two cents :)

2024-05-16 17:48 UTC, tekcay commented on src/main/java/gtb/api/unification/materials/info/GTBMaterialIconSet.java
`GTBMaterialIconType` has the same thing, so duplicate class, move it there :)

2024-05-16 18:45 UTC, jude123412 commented
I agree and I'll get right on moving them 😉

2024-05-16 21:17 UTC, jude123412 commented
New commitment, hopefully its all ok :)

2024-05-17 07:20 UTC, jude123412 reviewed
Everything should be working properly now.

2024-05-18 09:08 UTC, closed without merging